require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
-- require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.illuminate"
require "user.indentline"
require "user.alpha"
require "user.lsp"
require 'user.import-cost'
-- require "user.dap"
require 'user.coqCmp'
require "user.whichKey"
require "user.typescript"
require "user.tabout"
require("scope").setup()
-- require "user.colorizer"
vim.cmd(":COQnow --shut-up")
vim.cmd(":set laststatus=3")
vim.g.UltiSnipsExpandTrigger="<alt>"
vim.g.UltiSnipsJumpForwardTrigger="<c-b>"
vim.g.UltiSnipsJumpBackwardTrigger="<c-z>"
